version: '3.8'

services:
  elior-fitness:
    build: .
    ports:
      - "8000:8000"  # FastAPI accessible on port 8000 locally
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
      - railway_data:/data
    environment:
      # Universal configuration - works with any reverse proxy
      # For local development with Caddy, set your domain here
      - DOMAIN=${DOMAIN:-localhost}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:8000,http://127.0.0.1:3000,http://127.0.0.1:8000}
      - LOG_LEVEL=INFO
      - PORT=8000
      - DATABASE_PATH=/data/app.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 

volumes:
  railway_data:
    external: true 