services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - sqlite_data:/app/data  # Mount volume for SQLite database
    environment:
      - DATABASE_URL=sqlite:///./data/elior_fitness.db
      - JWT_SECRET=your-secret-key-here
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: >
      sh -c "
        echo 'Starting the application with SQLite...'
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  sqlite_data: 