version: '3.8'

services:
  elior-fitness:
    build: .
    ports:
      - "8000:80"  # Frontend accessible on port 8000
      - "8001:8000"  # Internal API access on port 8001
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - DOMAIN=localhost
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 