version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: elior-api-dev
    ports:
      - "3000:80"
    volumes:
      - ./uploads:/app/uploads
      - sqlite_data:/app/data
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./data/elior_fitness.db
      - JWT_SECRET=dev-secret-key-for-testing-only
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173,http://localhost
      - DOMAIN=localhost
      - MAX_FILE_SIZE=10485760
      - UPLOAD_DIR=/app/uploads
    restart: unless-stopped

volumes:
  sqlite_data: 